language: node_js
node_js:
  - "0.10"
before_script:
  - if [[ $(node -v) =~ ^v4.* ]]; then export __node_harmony=--harmony; fi
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
